const SESSION_ID = "SADIYA-MD=j84ilBSR#SGORfVVbkQKB2UBPgLYHjZrSWxF4ELwAlhE-96OyYHI"
const BOT_NUMBER = "94779510013"
const GITHUB_AUTH_TOKEN = "IriS7JyYT0MeqvfMIHDtj4dtfgFEoj082mM9"

module.exports = {SESSION_ID,BOT_NUMBER,GITHUB_AUTH_TOKEN}
